version: "3.8"

services:
    traefik:
        image: traefik:latest
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/traefik:/etc/traefik

        networks:
            - traefik_default
        deploy:
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: on-failure

    bot_server:
        image: ghcr.io/project-email-forwarding-telegram-bot/bot-server:latest
        environment:
            - ENVIRONMENT=production
        secrets:
            - REDIS_REST_TOKEN
            - TELEGRAM_BOT_TOKEN
        networks:
            - traefik_default
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.bot_server.rule=Host(`bot-server.email-forwarding-telegram-bot.cfd`)"
                - "traefik.http.routers.bot_server.tls.certresolver=acmeResolver"
                - "traefik.http.routers.bot_server.entrypoints=websecure"
                - "traefik.http.services.bot_server.loadbalancer.server.port=8443"
                - "traefik.http.services.bot_server.loadbalancer.server.scheme=http"

secrets:
    REDIS_REST_TOKEN:
        external: true
    TELEGRAM_BOT_TOKEN:
        external: true

networks:
    traefik_default:
        driver: overlay
        attachable: true
