version: "3.8"

services:
    bot_server:
        image: ghcr.io/project-email-forwarding-telegram-bot/bot-server:latest
        ports:
            - "8443:8443"
        environment:
            - ENVIRONMENT=production
        secrets:
            - REDIS_REST_TOKEN
            - TELEGRAM_BOT_TOKEN
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.bot_server.rule=Host(`bot-server.email-forwarding-telegram-bot.cfd`)"
                - "traefik.http.routers.bot_server.tls.certresolver=acmeResolver"
                - "traefik.http.services.bot_server.loadbalancer.server.port=8443"
                - "traefik.http.services.bot_server.servers.scheme=http"

secrets:
    REDIS_REST_TOKEN:
        external: true
    TELEGRAM_BOT_TOKEN:
        external: true

networks:
    traefik_default:
        external: true
