api:
    dashboard: true
    insecure: false

entryPoints:
    web:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https

    websecure:
        address: ":443"
        http:
            tls:
                certResolver: acmeResolver

certificatesResolvers:
    acmeResolver:
        acme:
            email: romeosarkar2002@gmail.com
            storage: /etc/traefik/certs/acme.json
            httpChallenge:
                entryPoint: web

providers:
    swarm:
        endpoint: "unix:///var/run/docker.sock"
