api:
    dashboard: true
    insecure: true

entryPoints:
    web:
        address: ":80"

    websecure:
        address: ":443"

certificatesResolvers:
    acmeResolver:
        acme:
            email: romeosarkar2002@gmail.com
            storage: /etc/traefik/acme.json
            httpChallenge:
                entryPoint: web

providers:
    swarm:
        endpoint: "unix:///var/run/docker.sock"
