name: Build and push a docker image to the `Github Container Registry`

on:
    push:
        branches: ["main"]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
        runs-on: ["self-hosted"]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Log in to the `Github Container Registry`
              uses: docker/login-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  context: .
                  path: ./dockerfile
