name: Build and push a docker image to the `Github Container Registry`

on:
    push:
        branches: ["main"]

env:
    REGISTRY: ghcr.io

jobs:
    build-and-push-image:
        runs-on: ["Linux", "self-hosted"]
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Echo `actor` and `actor_id`
              run: 'echo "Actor: ${{ github.actor }} | Actor ID: ${{ github.actor_id }}"'

            - name: Log in to the `Github Container Registry`
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Echo user
              run: whoami

            - name: Docker metadata
              uses: docker/metadata-action@v5
              id: meta
              with:
                  images: ${{ env.REGISTRY }}/${{ github.repository }}
                  tags: type=raw,value={{ branch }}_d{{ date 'YYYY-MM-DD' tz='Asia/Kolkata' }}_t{{ date 'HH-mm-ss' tz='Asia/Kolkata' }}_0x{{ sha }}

            - name: Echo `tags`
              run: |
                  echo ${{ steps.meta.outputs.tags }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  context: .
                  file: ./dockerfile
                  tags: ${{ steps.meta.outputs.tags }}
